
package com;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "libraryPort", targetNamespace = "http://www.examples.com/wsdl/HelloService.wsdl")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LibraryPort {


    /**
     * 
     * @param libraryRequest
     * @return
     *     returns com.LibraryResponse
     */
    @WebMethod(operationName = "Library")
    @WebResult(name = "LibraryResponse", targetNamespace = "http://www.examples.com/wsdl/HelloService.wsdl", partName = "LibraryResponse")
    public LibraryResponse library(
        @WebParam(name = "LibraryRequest", targetNamespace = "http://www.examples.com/wsdl/HelloService.wsdl", partName = "LibraryRequest")
        LibraryRequest libraryRequest);

}
